<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXvgf42A\coreAntCTO_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXvgf42A/coreAntCTO_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXvgf42A.legacy');

    return;
}

if (!\class_exists(coreAntCTO_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXvgf42A\coreAntCTO_KernelDevDebugContainer::class, coreAntCTO_KernelDevDebugContainer::class, false);
}

return new \ContainerXvgf42A\coreAntCTO_KernelDevDebugContainer([
    'container.build_hash' => 'Xvgf42A',
    'container.build_id' => '591c1758',
    'container.build_time' => 1554648661,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXvgf42A');
