<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOrIQ3I2\coreAntCTO_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOrIQ3I2/coreAntCTO_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOrIQ3I2.legacy');

    return;
}

if (!\class_exists(coreAntCTO_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOrIQ3I2\coreAntCTO_KernelDevDebugContainer::class, coreAntCTO_KernelDevDebugContainer::class, false);
}

return new \ContainerOrIQ3I2\coreAntCTO_KernelDevDebugContainer([
    'container.build_hash' => 'OrIQ3I2',
    'container.build_id' => '74eb8f4d',
    'container.build_time' => 1554649921,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOrIQ3I2');
