<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXjDy2hf\coreAntCTO_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXjDy2hf/coreAntCTO_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXjDy2hf.legacy');

    return;
}

if (!\class_exists(coreAntCTO_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXjDy2hf\coreAntCTO_KernelDevDebugContainer::class, coreAntCTO_KernelDevDebugContainer::class, false);
}

return new \ContainerXjDy2hf\coreAntCTO_KernelDevDebugContainer([
    'container.build_hash' => 'XjDy2hf',
    'container.build_id' => '03bf654a',
    'container.build_time' => 1554311824,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXjDy2hf');
